/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary": "#7b4d00",
        "on-tertiary-container": "#fff2e7",
        "tertiary-fixed": "#ffddb8",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#dce9ff",
        "on-tertiary-fixed": "#2a1700",
        "surface-tint": "#006d30",
        "on-secondary-container": "#fffbff",
        "background": "#f8f9ff",
        "secondary": "#4648d4",
        "surface-bright": "#f8f9ff",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#c0c1ff",
        "primary-container": "#15803d",
        "inverse-primary": "#79db8d",
        "surface-dim": "#ccdbf3",
        "on-background": "#0d1c2e",
        "secondary-container": "#6063ee",
        "primary-fixed": "#95f8a7",
        "on-secondary-fixed": "#07006c",
        "error": "#ba1a1a",
        "secondary-fixed": "#e1e0ff",
        "surface": "#f8f9ff",
        "on-error-container": "#93000a",
        "on-primary-container": "#d3ffd5",
        "primary": "#00652c",
        "inverse-surface": "#233144",
        "surface-container": "#e6eeff",
        "outline": "#6f7a6e",
        "on-tertiary-fixed-variant": "#653e00",
        "on-primary-fixed-variant": "#005323",
        "on-secondary-fixed-variant": "#2f2ebe",
        "tertiary-fixed-dim": "#ffb95f",
        "surface-container-low": "#eff4ff",
        "tertiary-container": "#9c6300",
        "on-surface": "#0d1c2e",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "surface-container-highest": "#d5e3fc",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#eaf1ff",
        "outline-variant": "#becabc",
        "primary-fixed-dim": "#79db8d",
        "on-primary-fixed": "#00210a",
        "on-surface-variant": "#3f493f",
        "surface-variant": "#d5e3fc",
        "on-secondary": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontSize: {
        'tiny': '0.55rem',
        'xxs': '0.625rem',
      }
    },
  },
  plugins: [],
}
